fix: Avoid double continuation resume in DeliveryMechanismAlert
In testing the alert delivery mechanism began logging:

  Fatal error: SWIFT TASK CONTINUATION MISUSE: present(title:body:)
  tried to resume its continuation more than once

This was from a misunderstanding when writing this block of code. The
beginSheetModal's completionHandler callback seems to always fire, even
when .endSheet was called. (In this case, the modalResponse passed was
-1000.) I mistakenly believed this handler was only triggered for user
actions.